# Site settings
title: The Reading Line
email: thereadingline@gmail.com
description: "The Reading Line is a non-profit organization that hosts book rides annually."
about: Making our city a better place, one street and one book at a time.
url: http://thereadingline.ca

google-analytics: UA-79717942-3

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/thereadingline
  - title: facebook
    url: https://www.facebook.com/thereadingline
  - title: instagram
    url: https://www.instagram.com/thereadingline/
  - title: envelope-o
    url: mailto:thereadingline@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

include: [_pages]
